'use client';
import { useState } from 'react';
import { Tag, Plus, Percent, DollarSign, Calendar, X } from 'lucide-react';
import { useLocale } from '@/lib/locale/LocaleProvider';

export interface Discount { id: string; code: string; type: 'percent'|'fixed'; value: number; minOrder: number; maxUses: number; usedCount: number; expiresAt: number; active: boolean; }

export function DiscountManager({ discounts = [], onCreate, onToggle, onDelete }: { discounts: Discount[]; onCreate?: (d: Omit<Discount,'id'|'usedCount'>) => void; onToggle?: (id: string) => void; onDelete?: (id: string) => void; }) {
  const { formatCurrency, formatDate } = useLocale();
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ code: '', type: 'percent' as const, value: 10, minOrder: 0, maxUses: 100, days: 30 });
  const handleCreate = () => { onCreate?.({ code: form.code.toUpperCase(), type: form.type, value: form.value, minOrder: form.minOrder, maxUses: form.maxUses, expiresAt: Date.now()+form.days*86400000, active: true }); setShowCreate(false); setForm({ code: '', type: 'percent', value: 10, minOrder: 0, maxUses: 100, days: 30 }); };
  return (<div className="space-y-6">
    <div className="flex items-center justify-between"><h2 className="text-xl font-bold text-white flex items-center gap-2"><Tag className="text-cyan-400"/>Discounts</h2><button onClick={()=>setShowCreate(!showCreate)} className="flex items-center gap-1.5 px-4 py-2 bg-cyan-500/20 border border-cyan-500/30 rounded-xl text-cyan-400 text-sm font-bold"><Plus size={14}/>Create Code</button></div>
    {showCreate&&<div className="bg-white/3 border border-white/10 rounded-xl p-5 space-y-4"><div className="grid grid-cols-2 gap-4"><input type="text" value={form.code} onChange={e => setForm({...form,code:e.target.value})} className="px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white text-sm uppercase focus:outline-none"/><select value={form.type} onChange={e => setForm({...form,type:e.target.value as any})} className="px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white text-sm"><option value="percent">Percentage</option><option value="fixed">Fixed Amount</option></select><input type="number" value={form.value} onChange={e => setForm({...form,value:parseFloat(e.target.value)||0})} className="px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white text-sm focus:outline-none"/><input type="number" value={form.maxUses} onChange={e => setForm({...form,maxUses:parseInt(e.target.value)||0})} className="px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white text-sm focus:outline-none"/></div><div className="flex gap-3"><button onClick={()=>setShowCreate(false)} className="flex-1 py-2.5 border border-white/10 text-gray-400 rounded-xl font-bold">Cancel</button><button onClick={handleCreate} disabled={!form.code} className="flex-1 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-xl font-bold disabled:opacity-50">Create</button></div></div>}
    <div className="space-y-2">{discounts.map(d=>(<div key={d.id} className="flex items-center justify-between p-4 bg-white/3 border border-white/5 rounded-xl"><div className="flex items-center gap-3"><code className="px-2 py-1 bg-cyan-500/10 text-cyan-400 rounded font-bold text-sm">{d.code}</code><span className="text-white text-sm">{d.type==='percent'?`${d.value}% off`:`${formatCurrency(d.value)} off`}</span><span className="text-gray-500 text-xs">{d.usedCount}/{d.maxUses} used</span></div><div className="flex items-center gap-2"><button onClick={()=>onToggle?.(d.id)} className={`px-2.5 py-1 rounded-lg text-xs font-bold ${d.active?'bg-emerald-500/20 text-emerald-400':'bg-gray-500/20 text-gray-400'}`}>{d.active?'Active':'Paused'}</button><button onClick={()=>onDelete?.(d.id)} className="p-1.5 text-gray-500 hover:text-red-400"><X size={14}/></button></div></div>))}</div>
  </div>);
}
