-- Migration: Add missing community/social/gamification tables
-- Generated by audit: tables used in API routes but missing from schema

CREATE TABLE IF NOT EXISTS community_posts (
  id           BIGSERIAL PRIMARY KEY,
  author_address VARCHAR(42) NOT NULL,
  content      TEXT        NOT NULL,
  image_url    TEXT,
  likes        INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_community_posts_author ON community_posts(author_address);
CREATE INDEX IF NOT EXISTS idx_community_posts_created ON community_posts(created_at DESC);

CREATE TABLE IF NOT EXISTS market_stories (
  id           BIGSERIAL PRIMARY KEY,
  merchant_address VARCHAR(42),
  title        TEXT        NOT NULL,
  content      TEXT,
  image_url    TEXT,
  posted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at   TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  view_count   INTEGER     NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_market_stories_expires ON market_stories(expires_at);

CREATE TABLE IF NOT EXISTS user_achievements (
  id           BIGSERIAL PRIMARY KEY,
  user_address VARCHAR(42) NOT NULL,
  achievement_id TEXT      NOT NULL,
  earned_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata     JSONB,
  UNIQUE(user_address, achievement_id)
);
CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON user_achievements(user_address);

-- user_gamification table (referenced by gamification API)
CREATE TABLE IF NOT EXISTS user_gamification (
  user_id      VARCHAR(42)  PRIMARY KEY,
  xp           INTEGER      NOT NULL DEFAULT 0,
  level        INTEGER      NOT NULL DEFAULT 1,
  badges       JSONB        NOT NULL DEFAULT '[]',
  streak_days  INTEGER      NOT NULL DEFAULT 0,
  last_active  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
