-- Revert FORCE RLS while keeping RLS enabled policies in place.
ALTER TABLE friendships NO FORCE ROW LEVEL SECURITY;
ALTER TABLE endorsements NO FORCE ROW LEVEL SECURITY;
ALTER TABLE proposals NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_rewards NO FORCE ROW LEVEL SECURITY;
ALTER TABLE messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_portfolios NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
