/**
 * Badge Registry - Frontend mirror of BadgeRegistry.sol
 * Maps badge IDs to display information
 */

import { keccak256, toBytes } from 'viem'

// Badge ID generator (matches Solidity keccak256)
export const getBadgeId = (name: string): `0x${string}` => {
  return keccak256(toBytes(name))
}

// Badge metadata type
export interface BadgeMetadata {
  id: `0x${string}`
  name: string
  displayName: string
  description: string
  category: string
  icon: string
  points: number
  duration: number // 0 = permanent, otherwise seconds
  isPermanent: boolean
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary' | 'Mythic'
  earnRequirement: string
}

// Badge Registry
export const BADGE_REGISTRY: Record<string, BadgeMetadata> = {
  // Pioneer & Foundation
  PIONEER: {
    id: getBadgeId('PIONEER'),
    name: 'PIONEER',
    displayName: 'Pioneer',
    description: 'First 10,000 users who joined VFIDE and believed in integrity over wealth',
    category: 'Pioneer & Foundation',
    icon: '🏁',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Legendary',
    earnRequirement: 'Be among the first 10,000 users to join',
  },
  GENESIS_PRESALE: {
    id: getBadgeId('GENESIS_PRESALE'),
    name: 'GENESIS_PRESALE',
    displayName: 'Genesis Presale',
    description: 'Participated in the initial presale and supported VFIDE from day one',
    category: 'Pioneer & Foundation',
    icon: '💎',
    points: 40,
    duration: 0,
    isPermanent: true,
    rarity: 'Legendary',
    earnRequirement: 'Participate in the genesis presale',
  },
  FOUNDING_MEMBER: {
    id: getBadgeId('FOUNDING_MEMBER'),
    name: 'FOUNDING_MEMBER',
    displayName: 'Founding Member',
    description: 'Among the first 1,000 users to achieve elite status (800+ ProofScore)',
    category: 'Pioneer & Foundation',
    icon: '👑',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Mythic',
    earnRequirement: 'Be in the first 1,000 to reach 800+ ProofScore',
  },
  
  // Activity & Participation
  ACTIVE_TRADER: {
    id: getBadgeId('ACTIVE_TRADER'),
    name: 'ACTIVE_TRADER',
    displayName: 'Active Trader',
    description: 'Completed 50+ commerce transactions in 90 days',
    category: 'Activity & Participation',
    icon: '📊',
    points: 20,
    duration: 90 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Uncommon',
    earnRequirement: '50+ transactions in 90 days (min $50 each)',
  },
  GOVERNANCE_VOTER: {
    id: getBadgeId('GOVERNANCE_VOTER'),
    name: 'GOVERNANCE_VOTER',
    displayName: 'Governance Voter',
    description: 'Voted on 10+ DAO proposals',
    category: 'Activity & Participation',
    icon: '🗳️',
    points: 25,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Uncommon',
    earnRequirement: 'Vote on 10+ DAO proposals',
  },
  POWER_USER: {
    id: getBadgeId('POWER_USER'),
    name: 'POWER_USER',
    displayName: 'Power User',
    description: 'Engaged in all ecosystem features (voting, commerce, endorsements)',
    category: 'Activity & Participation',
    icon: '⚡',
    points: 40,
    duration: 90 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Rare',
    earnRequirement: 'Use 3+ different features (vote, trade, endorse)',
  },
  DAILY_CHAMPION: {
    id: getBadgeId('DAILY_CHAMPION'),
    name: 'DAILY_CHAMPION',
    displayName: 'Daily Champion',
    description: 'Made at least one transaction every day for 30 consecutive days',
    category: 'Activity & Participation',
    icon: '🔥',
    points: 15,
    duration: 30 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Common',
    earnRequirement: '30-day consecutive activity streak',
  },
  
  // Trust & Community
  TRUSTED_ENDORSER: {
    id: getBadgeId('TRUSTED_ENDORSER'),
    name: 'TRUSTED_ENDORSER',
    displayName: 'Trusted Endorser',
    description: 'Made 5+ good endorsements of users who maintained high trust',
    category: 'Trust & Community',
    icon: '🤝',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: '5+ endorsements of users who kept >700 score for 6+ months',
  },
  COMMUNITY_BUILDER: {
    id: getBadgeId('COMMUNITY_BUILDER'),
    name: 'COMMUNITY_BUILDER',
    displayName: 'Community Builder',
    description: 'Recruited 10+ users who each achieved meaningful participation',
    category: 'Trust & Community',
    icon: '🏗️',
    points: 35,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Recruit 10 users who reach 600+ ProofScore',
  },
  MENTOR: {
    id: getBadgeId('MENTOR'),
    name: 'MENTOR',
    displayName: 'Mentor',
    description: 'Helped 5+ new users learn the system and reach governance threshold',
    category: 'Trust & Community',
    icon: '🎓',
    points: 30,
    duration: 365 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Rare',
    earnRequirement: 'Help 5 new users reach 540+ ProofScore',
  },
  
  // Commerce & Merchants
  VERIFIED_MERCHANT: {
    id: getBadgeId('VERIFIED_MERCHANT'),
    name: 'VERIFIED_MERCHANT',
    displayName: 'Verified Merchant',
    description: 'Completed 100+ successful transactions with zero disputes',
    category: 'Commerce & Merchants',
    icon: '✅',
    points: 40,
    duration: 365 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Rare',
    earnRequirement: '100+ transactions, 0 disputes, 700+ ProofScore',
  },
  ELITE_MERCHANT: {
    id: getBadgeId('ELITE_MERCHANT'),
    name: 'ELITE_MERCHANT',
    displayName: 'Elite Merchant',
    description: '1,000+ transactions with >$100k volume and near-perfect rating',
    category: 'Commerce & Merchants',
    icon: '⭐',
    points: 60,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Epic',
    earnRequirement: '1,000+ transactions, $100k+ volume, 4.8+ rating',
  },
  ZERO_DISPUTE: {
    id: getBadgeId('ZERO_DISPUTE'),
    name: 'ZERO_DISPUTE',
    displayName: 'Zero Dispute',
    description: '200+ transactions with perfect dispute-free record',
    category: 'Commerce & Merchants',
    icon: '🛡️',
    points: 25,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Rare',
    earnRequirement: '200+ transactions with 0 disputes',
  },
  
  // Security & Integrity
  FRAUD_HUNTER: {
    id: getBadgeId('FRAUD_HUNTER'),
    name: 'FRAUD_HUNTER',
    displayName: 'Fraud Hunter',
    description: 'Reported 3+ confirmed fraud cases, protecting the community',
    category: 'Security & Integrity',
    icon: '🕵️',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Report 3+ confirmed fraud cases (DAO verified)',
  },
  CLEAN_RECORD: {
    id: getBadgeId('CLEAN_RECORD'),
    name: 'CLEAN_RECORD',
    displayName: 'Clean Record',
    description: 'Maintained flawless behavior with zero negative events for 1 year',
    category: 'Security & Integrity',
    icon: '📜',
    points: 20,
    duration: 365 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Common',
    earnRequirement: '1 year with no punishments or disputes',
  },
  REDEMPTION: {
    id: getBadgeId('REDEMPTION'),
    name: 'REDEMPTION',
    displayName: 'Redemption',
    description: 'Recovered from past mistakes through sustained good behavior',
    category: 'Security & Integrity',
    icon: '🌟',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: '6+ months of good behavior after penalty',
  },
  GUARDIAN: {
    id: getBadgeId('GUARDIAN'),
    name: 'GUARDIAN',
    displayName: 'Guardian',
    description: 'Maintained elite trust status without dropping below 700 for 2+ years',
    category: 'Security & Integrity',
    icon: '🛡️👁️',
    points: 40,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'ProofScore never below 700 for 2+ years',
  },
  
  // Achievements & Milestones
  ELITE_ACHIEVER: {
    id: getBadgeId('ELITE_ACHIEVER'),
    name: 'ELITE_ACHIEVER',
    displayName: 'Elite Achiever',
    description: 'Reached ProofScore 900+ (top 5% of all users)',
    category: 'Achievements & Milestones',
    icon: '🏆',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Reach ProofScore 900+',
  },
  WHALE_SLAYER: {
    id: getBadgeId('WHALE_SLAYER'),
    name: 'WHALE_SLAYER',
    displayName: 'Whale Slayer',
    description: 'Won a DAO vote against a whale with 10x your token holdings',
    category: 'Achievements & Milestones',
    icon: '🐋⚔️',
    points: 25,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Win DAO vote where opponent had 10x your tokens',
  },
  DIVERSIFICATION_MASTER: {
    id: getBadgeId('DIVERSIFICATION_MASTER'),
    name: 'DIVERSIFICATION_MASTER',
    displayName: 'Diversification Master',
    description: 'Participated in all ecosystem features',
    category: 'Achievements & Milestones',
    icon: '🎯',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Use all features: DAO, commerce, vault, endorsements, badges',
  },
  
  // Education & Contribution
  EDUCATOR: {
    id: getBadgeId('EDUCATOR'),
    name: 'EDUCATOR',
    displayName: 'Educator',
    description: 'Created 5+ educational content pieces helping others learn VFIDE',
    category: 'Education & Contribution',
    icon: '👨‍🏫',
    points: 30,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Rare',
    earnRequirement: 'Create 5+ guides/videos (DAO approved)',
  },
  CONTRIBUTOR: {
    id: getBadgeId('CONTRIBUTOR'),
    name: 'CONTRIBUTOR',
    displayName: 'Contributor',
    description: 'Made meaningful code, design, or content contribution to VFIDE',
    category: 'Education & Contribution',
    icon: '💻',
    points: 40,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'GitHub PR merged or DAO-approved contribution',
  },
  BUG_BOUNTY: {
    id: getBadgeId('BUG_BOUNTY'),
    name: 'BUG_BOUNTY',
    displayName: 'Bug Bounty',
    description: 'Reported a security vulnerability (points vary by severity)',
    category: 'Education & Contribution',
    icon: '🐛',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Report security vulnerability (20-100 points by severity)',
  },
  TRANSLATOR: {
    id: getBadgeId('TRANSLATOR'),
    name: 'TRANSLATOR',
    displayName: 'Translator',
    description: 'Translated VFIDE documentation/UI to a new language',
    category: 'Education & Contribution',
    icon: '🌐',
    points: 25,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Complete translation package for new language',
  },

  // Trading & Volume Tiers
  BRONZE_TRADER: {
    id: getBadgeId('BRONZE_TRADER'),
    name: 'BRONZE_TRADER',
    displayName: 'Bronze Trader',
    description: 'Completed 10 transactions, showing early platform engagement',
    category: 'Trading & Volume',
    icon: '🥉',
    points: 10,
    duration: 90 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Common',
    earnRequirement: 'Complete 10 transactions',
  },
  SILVER_TRADER: {
    id: getBadgeId('SILVER_TRADER'),
    name: 'SILVER_TRADER',
    displayName: 'Silver Trader',
    description: 'Completed 100 transactions with growing expertise',
    category: 'Trading & Volume',
    icon: '🥈',
    points: 20,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Uncommon',
    earnRequirement: 'Complete 100 transactions',
  },
  GOLD_TRADER: {
    id: getBadgeId('GOLD_TRADER'),
    name: 'GOLD_TRADER',
    displayName: 'Gold Trader',
    description: 'Completed 500+ transactions, a true platform veteran',
    category: 'Trading & Volume',
    icon: '🥇',
    points: 35,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Complete 500 transactions',
  },
  WHALE: {
    id: getBadgeId('WHALE'),
    name: 'WHALE',
    displayName: 'Whale',
    description: 'High-volume trader with 1000+ transactions',
    category: 'Trading & Volume',
    icon: '🐋',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Complete 1,000+ transactions',
  },

  // Governance & Voting
  VOTING_STREAK_5: {
    id: getBadgeId('VOTING_STREAK_5'),
    name: 'VOTING_STREAK_5',
    displayName: 'Voting Streak: 5',
    description: 'Voted on 5 consecutive proposals without missing any',
    category: 'Governance & Voting',
    icon: '🗳️',
    points: 15,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Common',
    earnRequirement: 'Vote on 5 consecutive proposals',
  },
  VOTING_STREAK_10: {
    id: getBadgeId('VOTING_STREAK_10'),
    name: 'VOTING_STREAK_10',
    displayName: 'Voting Streak: 10',
    description: 'Voted on 10 consecutive proposals, showing consistent engagement',
    category: 'Governance & Voting',
    icon: '🗳️',
    points: 25,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Uncommon',
    earnRequirement: 'Vote on 10 consecutive proposals',
  },
  VOTING_STREAK_20: {
    id: getBadgeId('VOTING_STREAK_20'),
    name: 'VOTING_STREAK_20',
    displayName: 'Voting Streak: 20',
    description: 'Voted on 20 consecutive proposals, a true governance champion',
    category: 'Governance & Voting',
    icon: '🗳️',
    points: 40,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Vote on 20 consecutive proposals',
  },
  PROPOSAL_CREATOR: {
    id: getBadgeId('PROPOSAL_CREATOR'),
    name: 'PROPOSAL_CREATOR',
    displayName: 'Proposal Creator',
    description: 'Created a proposal that passed DAO vote',
    category: 'Governance & Voting',
    icon: '📝',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Create 1 proposal that passes',
  },

  // Social & Endorsements
  ENDORSEMENT_100: {
    id: getBadgeId('ENDORSEMENT_100'),
    name: 'ENDORSEMENT_100',
    displayName: 'Endorsement Milestone: 100',
    description: 'Given 100+ endorsements, building community trust',
    category: 'Social & Endorsements',
    icon: '🤝',
    points: 20,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Uncommon',
    earnRequirement: 'Give 100 endorsements',
  },
  ENDORSEMENT_500: {
    id: getBadgeId('ENDORSEMENT_500'),
    name: 'ENDORSEMENT_500',
    displayName: 'Endorsement Milestone: 500',
    description: 'Given 500+ endorsements, a true community supporter',
    category: 'Social & Endorsements',
    icon: '🤝',
    points: 35,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Give 500 endorsements',
  },
  ENDORSEMENT_1000: {
    id: getBadgeId('ENDORSEMENT_1000'),
    name: 'ENDORSEMENT_1000',
    displayName: 'Endorsement Milestone: 1000',
    description: 'Given 1000+ endorsements, legendary trust builder',
    category: 'Social & Endorsements',
    icon: '🤝',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Give 1,000 endorsements',
  },
  HIGHLY_ENDORSED: {
    id: getBadgeId('HIGHLY_ENDORSED'),
    name: 'HIGHLY_ENDORSED',
    displayName: 'Highly Endorsed',
    description: 'Received 50+ endorsements from community members',
    category: 'Social & Endorsements',
    icon: '⭐',
    points: 30,
    duration: 180 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Rare',
    earnRequirement: 'Receive 50+ endorsements',
  },

  // Time-Based & Milestones
  EARLY_BIRD: {
    id: getBadgeId('EARLY_BIRD'),
    name: 'EARLY_BIRD',
    displayName: 'Early Bird',
    description: 'Consistently active before 8 AM for 30 days',
    category: 'Time & Activity Patterns',
    icon: '🌅',
    points: 15,
    duration: 90 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Common',
    earnRequirement: 'Be active before 8 AM for 30 days',
  },
  NIGHT_OWL: {
    id: getBadgeId('NIGHT_OWL'),
    name: 'NIGHT_OWL',
    displayName: 'Night Owl',
    description: 'Consistently active after 10 PM for 30 days',
    category: 'Time & Activity Patterns',
    icon: '🦉',
    points: 15,
    duration: 90 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Common',
    earnRequirement: 'Be active after 10 PM for 30 days',
  },
  WEEKEND_WARRIOR: {
    id: getBadgeId('WEEKEND_WARRIOR'),
    name: 'WEEKEND_WARRIOR',
    displayName: 'Weekend Warrior',
    description: 'Most active on weekends for 2 months',
    category: 'Time & Activity Patterns',
    icon: '🏖️',
    points: 20,
    duration: 90 * 24 * 60 * 60,
    isPermanent: false,
    rarity: 'Uncommon',
    earnRequirement: 'Primary activity on weekends for 8 weeks',
  },
  ONE_YEAR_ANNIVERSARY: {
    id: getBadgeId('ONE_YEAR_ANNIVERSARY'),
    name: 'ONE_YEAR_ANNIVERSARY',
    displayName: 'One Year Anniversary',
    description: 'Celebrating one full year on VFIDE',
    category: 'Time & Activity Patterns',
    icon: '🎂',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: '365 days of membership',
  },
  TWO_YEAR_ANNIVERSARY: {
    id: getBadgeId('TWO_YEAR_ANNIVERSARY'),
    name: 'TWO_YEAR_ANNIVERSARY',
    displayName: 'Two Year Anniversary',
    description: 'Celebrating two years of dedicated platform use',
    category: 'Time & Activity Patterns',
    icon: '🎊',
    points: 50,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: '730 days of membership',
  },

  // Special Events & Achievements
  BETA_TESTER: {
    id: getBadgeId('BETA_TESTER'),
    name: 'BETA_TESTER',
    displayName: 'Beta Tester',
    description: 'Participated in platform beta testing phase',
    category: 'Special Events',
    icon: '🧪',
    points: 35,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Join during beta period',
  },
  HOLIDAY_2024: {
    id: getBadgeId('HOLIDAY_2024'),
    name: 'HOLIDAY_2024',
    displayName: 'Holiday 2024',
    description: 'Active during the 2024 holiday season event',
    category: 'Special Events',
    icon: '🎄',
    points: 15,
    duration: 0,
    isPermanent: true,
    rarity: 'Common',
    earnRequirement: 'Participate in Holiday 2024 event',
  },
  CONFERENCE_ATTENDEE: {
    id: getBadgeId('CONFERENCE_ATTENDEE'),
    name: 'CONFERENCE_ATTENDEE',
    displayName: 'Conference Attendee',
    description: 'Attended an official VFIDE conference or meetup',
    category: 'Special Events',
    icon: '🎤',
    points: 25,
    duration: 0,
    isPermanent: true,
    rarity: 'Uncommon',
    earnRequirement: 'Attend official VFIDE event',
  },
  
  // Content & Contribution
  DOCUMENTATION_HERO: {
    id: getBadgeId('DOCUMENTATION_HERO'),
    name: 'DOCUMENTATION_HERO',
    displayName: 'Documentation Hero',
    description: 'Contributed significant improvements to platform documentation',
    category: 'Content & Contribution',
    icon: '📚',
    points: 30,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Contribute to documentation (verified by team)',
  },
  TUTORIAL_CREATOR: {
    id: getBadgeId('TUTORIAL_CREATOR'),
    name: 'TUTORIAL_CREATOR',
    displayName: 'Tutorial Creator',
    description: 'Created high-quality tutorial content for the community',
    category: 'Content & Contribution',
    icon: '🎬',
    points: 25,
    duration: 0,
    isPermanent: true,
    rarity: 'Uncommon',
    earnRequirement: 'Create approved tutorial content',
  },
  AMBASSADOR: {
    id: getBadgeId('AMBASSADOR'),
    name: 'AMBASSADOR',
    displayName: 'Ambassador',
    description: 'Official VFIDE ambassador spreading platform awareness',
    category: 'Content & Contribution',
    icon: '🌟',
    points: 60,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Become official VFIDE ambassador (team approved)',
  },

  // Milestone Achievements
  TRANSACTION_MILESTONE_1K: {
    id: getBadgeId('TRANSACTION_MILESTONE_1K'),
    name: 'TRANSACTION_MILESTONE_1K',
    displayName: 'Transaction Milestone: 1K',
    description: 'Reached 1,000 total transactions',
    category: 'Milestone Achievements',
    icon: '🎯',
    points: 40,
    duration: 0,
    isPermanent: true,
    rarity: 'Rare',
    earnRequirement: 'Complete 1,000 transactions',
  },
  TRANSACTION_MILESTONE_5K: {
    id: getBadgeId('TRANSACTION_MILESTONE_5K'),
    name: 'TRANSACTION_MILESTONE_5K',
    displayName: 'Transaction Milestone: 5K',
    description: 'Reached 5,000 total transactions, a platform legend',
    category: 'Milestone Achievements',
    icon: '🎯',
    points: 60,
    duration: 0,
    isPermanent: true,
    rarity: 'Epic',
    earnRequirement: 'Complete 5,000 transactions',
  },
  PERFECT_SCORE: {
    id: getBadgeId('PERFECT_SCORE'),
    name: 'PERFECT_SCORE',
    displayName: 'Perfect Score',
    description: 'Achieved maximum ProofScore of 10,000',
    category: 'Milestone Achievements',
    icon: '💯',
    points: 100,
    duration: 0,
    isPermanent: true,
    rarity: 'Mythic',
    earnRequirement: 'Reach 10,000 ProofScore',
  },
}

// Helper functions
export const getAllBadges = (): BadgeMetadata[] => {
  return Object.values(BADGE_REGISTRY)
}

export const getBadgeByName = (name: string): BadgeMetadata | undefined => {
  return BADGE_REGISTRY[name]
}

export const getBadgeById = (id: `0x${string}`): BadgeMetadata | undefined => {
  return getAllBadges().find(badge => badge.id === id)
}

export const getBadgesByCategory = (category: string): BadgeMetadata[] => {
  return getAllBadges().filter(badge => badge.category === category)
}

export const getBadgeCategories = (): string[] => {
  return Array.from(new Set(getAllBadges().map(badge => badge.category)))
}

export const formatDuration = (seconds: number): string => {
  if (seconds === 0) return 'Permanent'
  const days = Math.floor(seconds / (24 * 60 * 60))
  return `${days} days`
}
